version: '3.7'

volumes:
  vue_cli_node_volume:

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuecli3
    ports:
      - 8080:8080
    volumes:
      - .:/app/
      - vue_cli_node_volume:/app/node_modules

    stdin_open: true
    tty: true
    command: /bin/sh
